"""Initial migration

Revision ID: 0ba1f71ac250
Revises: 
Create Date: 2025-03-21 12:40:05.637161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba1f71ac250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('Message_ID', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Message_ID')
    )
    op.create_table('providers',
    sa.Column('Provider_ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Contact', sa.String(length=20), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.String(length=200), nullable=True),
    sa.Column('Password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Provider_ID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('services',
    sa.Column('Service_ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Category', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('Service_ID')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bookings',
    sa.Column('Booking_ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Service_ID', sa.Integer(), nullable=False),
    sa.Column('Booking_Date', sa.DateTime(), nullable=False),
    sa.Column('Schedule_Date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Service_ID'], ['services.Service_ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('Booking_ID')
    )
    op.create_table('feedbacks',
    sa.Column('Feedback_ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Rating', sa.Float(), nullable=False),
    sa.Column('Comment', sa.Text(), nullable=True),
    sa.Column('Feedback_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['User_ID'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('Feedback_ID')
    )
    op.create_table('gallery',
    sa.Column('Image_ID', sa.Integer(), nullable=False),
    sa.Column('Service_ID', sa.Integer(), nullable=True),
    sa.Column('Image_Name', sa.String(length=150), nullable=False),
    sa.Column('Image_Description', sa.Text(), nullable=True),
    sa.Column('Image_Path', sa.String(length=255), nullable=False),
    sa.Column('Upload_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Service_ID'], ['services.Service_ID'], ),
    sa.PrimaryKeyConstraint('Image_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery')
    op.drop_table('feedbacks')
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('providers')
    op.drop_table('messages')
    # ### end Alembic commands ###
